jsonLogger: 
  disabledFields: ""
  logLocationInfo: "false"
  maskedFields: ""
  
sage:
 api:
  host: "api.intacct.com"
  basePath: "/ia"
  path: "/xml/xmlgw.phtml"
 login:
  userId: "SpinCar-Salesforce"
  userPass: "3e2gb+DL7jw"
  companyId: "SpinCar-sandbox"
  senderId: "SpinCar"
  senderPass: "Projectenlighet25$"  
 responseTimeout: "60000"
 reconnect:
  frequency: "2000"
  attempts: "3"
  
salesforce:
  tokenApi: "https://impel-ai--full.sandbox.my.salesforce.com/services/oauth2/token"
  clientId: "3MVG9yAfNLkSWumNZW2g.cwIoKSSGTQLuCFmYYZlZH.pihr4K5ROh7dFQ5Ck6d3ug1XRh5kx9xfolROLVoEza"
  clientSecret: "0F82B61F1483D464A8BAA2D9EE90CAC143217E63AD8F6DB9A4C781DD0E5397C7"
  grantType: "client_credentials"

objstore:
  expirationinterval: "60"
  maxentries:  "1"
  ttl: "60"